### ISSUE TITLE
Ardumoto_v15 Checklist 

### ISSUE THREAD

**Issue by edspark** [sparkfun/Ardumoto-Motor_Driver_Shield#1]
1) Is there a SparkFun Logo? [YES]
comment: There are two logos on the second sheet, I'm not sure if you want them both.

2) Does it pass DRC with top/bottom keepout layers on? [YES]
comment: Plenty of approved erros centered around the many jumpers (funky library) and the 15 mill vias under the IC.

3) Are there airwires after ratsnest? [YES]
comment: I found two air wires and have attached images of them both. 

4) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [NO]
comment: There are missing measurements for the standoffs. 

First air wire:
![first air wire](https://cloud.githubusercontent.com/assets/18684691/21814007/2f1c1da4-d715-11e6-87d0-00a6aef3bd32.JPG)

Second air wire:
![second_air_wire](https://cloud.githubusercontent.com/assets/18684691/21814015/3348a7f8-d715-11e6-9509-d3aa2dc18181.JPG)

**Comment by marshalltaylorSFE** [comment]
1.  Switched sheets, moved one "logo" to the other sheet (these are really symbols to silk shapes)
2.  These approved violations are acceptable
3.  Airwires fixed!
4.  Measures added!
