### ISSUE TITLE
Ardumoto Revision v15 Checklist

### ISSUE THREAD

**Issue by edspark** [sparkfun/Ardumoto-Motor_Driver_Shield#2]
1) If there are any DRC errors, have they all been approved? [YES]
comment: Many approved erros, double checked. 

2) Is the designer name included in tDocu? [NO]
comment: "Pete Dokter" is not included in "Designed By"

3) Is any silkscreen overlaid on vias? [YES]
comment: Looks good for the silk that is partly covering vias.

**Comment by marshalltaylorSFE** [comment]
1. OK
2. Name became buried under license after movement for measures, fixed.
3. "D7" is troublesome, but no better location is obvious, let's see how these look in proto hardware.
